payloads = [
{"tradingsymbol": "NIFTYBEES", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 1694, "price": 292.06, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "NIFTYBEES", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 1694, "price": 295.0, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "CPSEETF", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 535, "price": 93.09, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "CPSEETF", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 535, "price": 94.03, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "ITBEES", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 3609, "price": 39.69, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "ITBEES", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 3609, "price": 40.09, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "ICICIB22", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 172, "price": 116.89, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "ICICIB22", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 172, "price": 118.06, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "JUNIORBEES", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 132, "price": 749.33, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "JUNIORBEES", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 132, "price": 756.86, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "HDFCSML250", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 458, "price": 171.84, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "HDFCSML250", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 458, "price": 173.57, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "MID150BEES", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 258, "price": 230.04, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "MID150BEES", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 258, "price": 232.35, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "PSUBNKBEES", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 1067, "price": 93.64, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "PSUBNKBEES", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 1067, "price": 94.58, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "NIFTYIETF", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 211, "price": 290.6, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "NIFTYIETF", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 211, "price": 293.52, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "NEXT50IETF", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 292, "price": 73.2, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "NEXT50IETF", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 292, "price": 73.94, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "SETFNIF50", "exchange": "NSE", "transaction_type": "BUY", "order_type": "LIMIT", "quantity": 175, "price": 276.06, "product": "MIS", "validity": "DAY", "tag": "beta"},
{"tradingsymbol": "SETFNIF50", "exchange": "NSE", "transaction_type": "SELL", "order_type": "LIMIT", "quantity": 175, "price": 278.83, "product": "MIS", "validity": "DAY", "tag": "beta"}
]
